import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MarketContextProvider from "@/contexts/MarketContextProvider";
import Navbar from "@/components/navbar/Navbar";
import { fetchAllProducts } from "@/functions/server/database";
import SnackbarContextProvider from "@/contexts/SnackbarContextProvider";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // * Pre-renders on build
  // * Layout of main route group
  // * Sends allProducts to navbar which will be used by navbarMarket
  // * It wraps content with navbar and market context

  const allProducts = await fetchAllProducts();

  return (
    <MarketContextProvider>
      <Navbar allProducts={allProducts}></Navbar>
      <div className={styles.layout}>{children}</div>
    </MarketContextProvider>
  );
}
